version: '3.8'
services:
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
      - MYSQL_DATABASE=project
    volumes:
      - ./volumes/mysqsl:/var/lib/mysql
  redis:
    image: redis
    ports:
      - 6379:6379
